#version 430

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0, rgba8)  uniform image2D resultImage;
layout(push_constant)       uniform Parameters {
  // GLSL has uints.
  //   https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Scalars
  uint iResolution_x;
  uint iResolution_y;
} parameters;

const float iTime = 5.0;
vec2        iResolution;

float sdBox( vec3 p, vec3 b )
{
  vec3 q = abs(p) - b;
  return length(max(q,0.0)) + min(max(q.x,max(q.y,q.z)),0.0);
}

float sdPlane(vec3 p, vec3 n, float d) {
    return dot(p, n) + d;
}

float sdCylinder( vec3 p)
{
  vec3 c = vec3(2.0, 2.0, 2.0);
  return length(p.xz-c.xy)-c.z;
}

vec3 Color = vec3(1.0, 1.0, 1.0);

float sdf(vec3 p) {
    float step = 6.0;

    float cylDist = sdCylinder(p);
    float planceDist = sdPlane(p, vec3(0.04, 1.0, 0.0), 5.0);

    if (cylDist < planceDist) {
        Color = vec3(165.0 / 255.0, 157.0 / 255.0, 132.0 / 255.0);
        return cylDist;
    } else {
        Color = vec3(34.0 / 255.0 ,139.0 / 255.0,34.0 / 255.0);
        return planceDist;
    }
}

float raymarch(vec3 origin, vec3 dir) {
    float totalDist = 0.0;
    const float MAX_DISTANCE = 100.0;
    const float EPS = 0.01;
    vec3 pos;
    float dist;

    for (int i = 0; i < 100; i++) {
        pos = origin + totalDist * dir;
        dist = sdf(pos);

        if (dist < EPS)
            return totalDist;

        totalDist += dist;
        if (totalDist > MAX_DISTANCE) break;
    }
    return MAX_DISTANCE;
}

void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    vec2 uv = (fragCoord - 0.7 * iResolution.xy) / iResolution.y;

    vec3 rayDir = normalize(vec3(uv, 1.0));
    vec3 rayOrigin = vec3(10.0, 20.0, -60.0);

    float dist = raymarch(rayOrigin, rayDir);

    vec3 color = vec3(0.0);
    if (dist < 100.0) {
        vec3 hitPoint = rayOrigin + rayDir * dist;
        
        vec3 normal = normalize(vec3(
            sdf(hitPoint + vec3(0.01, 0, 0)) - sdf(hitPoint - vec3(0.01, 0, 0)),
            sdf(hitPoint + vec3(0, 0.01, 0)) - sdf(hitPoint - vec3(0, 0.01, 0)),
            sdf(hitPoint + vec3(0, 0, 0.01)) - sdf(hitPoint - vec3(0, 0, 0.01))
        ));

        vec3 lightPos = vec3(5.0 * sin(iTime), 5.0, 5.0 * cos(iTime));
        vec3 lightDir = normalize(lightPos - hitPoint);
        float diffuse = max(dot(normal, lightDir), 0.0);
        float ambient = 0.1;

        color = (ambient + diffuse) * Color;
    }

    fragColor = vec4(color, 1.0);
}


void main()
{
  iResolution = vec2(parameters.iResolution_x, parameters.iResolution_y);

  vec4 fragColor;
  vec2  fragCoord  = vec2(gl_GlobalInvocationID.xy);
  ivec2 iFragCoord = ivec2(gl_GlobalInvocationID.xy);
  mainImage(fragColor, fragCoord);

  if (iFragCoord.x < 1280 && iFragCoord.y < 720)
    imageStore(resultImage, iFragCoord, fragColor);
}
