#version 430

layout(local_size_x = 32, local_size_y = 32) in;

layout (binding = 0, rgba8) uniform image2D resultImage;

vec3 generateProceduralTexture(vec2 p) {
    return vec3(sin(p.x * 10.0), cos(p.y * 10.0), 1.0);
}

void main( )
{
    vec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec3 color = generateProceduralTexture(coord);
    
    imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), vec4(color, 1.0));
}
